### ISSUE TITLE
Issue about running docker and forming farmvibes cluster

### ISSUE THREAD

**Issue by MuhammadHammadBashir** [microsoft/farmvibes-ai#101]
I am following all the guidelines provided in link https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html.
I have all the specifications needed for system as I have window in system so using window subsystem linux ubuntu for the task.
1) I am stuck with the thing docker not running there.
2) Once I did the docker run (with sudo) the error raised is 
          stderr:
          docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: waiting for init preliminary setup: EOF: unknown.
          
          
            ╭───────────────────────────────────────────────────────────────────────────────────────────╮
          │                                                                                           │
          │    😿  If the above advice does not help, please let us know:                             │
          │    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
          │                                                                                           │
          │    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
          │                                                                                           │
          ╰───────────────────────────────────────────────────────────────────────────────────────────╯
3) Again I am stuck with docker not runniing for now.

Can you please help me how to do this.
Thanks in advance

**Comment by renatolfc** [comment]
Hello @MuhammadHammadBashir, you seem to be running an old version of the code that still uses the minikube backend.

We migrated away from minikube with the January 27th release. I recommend you do a `git pull` and recreate your cluster.

Please notice that if docker isn't working, FarmVibes.AI will also not work.

**Comment by rafaspadilha** [comment]
Closing this issue for now. @MuhammadHammadBashir, feel free to reopen if the problem persists.
