### ISSUE TITLE
Persistent 'dapr failed to process request' Error Causing Workflow Failures

### ISSUE THREAD

**Issue by click2cloud-sagarB** [microsoft/farmvibes-ai#104]
Dear Farmvibes Team,
We successfully generated timelapse of SpaceEye and vegitation indices by running workflow for the given farm but we had to run workflow multiple times because it failed to execute and returned the error "dapr failed to process request". We had to rerun workflow every time it gets failed because of this issue. Is there any way we can avoid this error so that we don't need to rerun workflow again and again for failed status?

Attached to this issue, you will find the following files for your reference:
- Log files for each of the pods involved in the process:
    1) terravibes-worker
    2) terravibes-orchestrator
    3) terravibes-rest-api
- A JSON file containing the running pods in our Kubernetes cluster.
- The .wkt file representing the farm for which we consistently encounter the "dapr failed to process request" error.

[Workflow_Error_Logs_Files.zip](https://github.com/microsoft/farmvibes-ai/files/11663710/Workflow_Error_Logs_Files.zip)

**Comment by rafaspadilha** [comment]
Hello, @click2cloud-sagarB. Thank you for raising the issue. 
The logs seem to be fine, as far as I've seen. Maybe they are from the successful run. Are you still experiencing this?
Next release will improve the stability of the cluster and we expect less issues with dapr and async.io.

**Comment by click2cloud-sagarB** [comment]
Hello Rafael, The dapr problem is something that we occasionally, but not frequently, experience.  Awaiting the upcoming release with the fix. Thank you.

**Comment by rafaspadilha** [comment]
Hi, @click2cloud-sagarB. Are you still experiencing this issue?

**Comment by click2cloud-sagarB** [comment]
Hi, @rafaspadilha Since the recent commit on September 6th, I haven't experienced this issue. If the same issue develops again, I will notify you.

**Comment by rafaspadilha** [comment]
Thank you, @click2cloud-sagarB . I'll close this issue for now, but feel free to reopen it if the issue arises again.

**Comment by shenoy10** [comment]
Hi,
Is there any update on this. I'm currently experiencing this issue as well

**Comment by rafaspadilha** [comment]
Hi, @shenoy10. Could you provide more details for us? Are you seeing this issue in any particular circumstance (does it happen when running the first workflow since cluster setup? Or when retrieving cached data?).

If possible, could you share some logs of a failed run with us?
