### ISSUE TITLE
get_default_vibe_client doesn't work 

### ISSUE THREAD

**Issue by jeantirole** [microsoft/farmvibes-ai#106]
Hello, 

I am trying to use [notebooks] to download data.
but "from vibe_core.client import get_default_vibe_client" doesn't seem to work well. 
The connection errors come out. 

![image](https://github.com/microsoft/farmvibes-ai/assets/63326859/685d6b2d-4447-4d77-89b2-65ca8c0f949d)
![image](https://github.com/microsoft/farmvibes-ai/assets/63326859/5893417e-4b44-412a-a7fd-b0c19b67bc5a)

ConnectionError: HTTPConnectionPool(host='192.168.49.2', port=30000): Max retries exceeded with url: /v0/system-metrics (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by brsilvarec** [comment]
Hi @jeantirole,

     Thanks for testing our platform. I believe your cluster is not installed. Have you tried to install the cluster using the steps in this page? https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html

**Comment by rafaspadilha** [comment]
Hi, @jeantirole. Any updates on this? Were you able to set up your cluster?

**Comment by rafaspadilha** [comment]
Closing this issue for now. @jeantirole, feel free to reopen it if your problem persists.
