### ISSUE TITLE
data_processing/clip/clip workflow doesn't make any effect

### ISSUE THREAD

**Issue by guvenakcoban** [microsoft/farmvibes-ai#111]
## Description
I am examining and testing how to use FarmVibes.AI. I noticed that it did not have any effect when I ran the Clip workflow. My aim is to obtain a TIFF file where only a specific polygon area is cut out and to work on this small file. As you can see from the output, the raster paths of the s2 task and the clip task are the same. Am I missing something?

Thanks.

## Yaml
```yaml
name: custom_workflow
sources:
  user_input:
    - s2.user_input
    - clip_raster.input_geometry
sinks:
  s2_raster: s2.raster
  clipped_raster: clip_raster.clipped_raster
parameters:
  pc_key: null
tasks:
  s2:
    workflow: data_ingestion/sentinel2/preprocess_s2
    parameters:
      pc_key: "@from(pc_key)"
  clip_raster:
    workflow: data_processing/clip/clip
edges:
  - origin: s2.raster
    destination:
      - clip_raster.raster
```

## Output
`
{'s2_raster': [Sentinel2Raster(id='838849f1-6a9e-4243-851a-9680fae2e861', time_range=(datetime.datetime(2023, 5, 14, 8, 45, 59, 24000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 14, 8, 45, 59, 24000, tzinfo=datetime.timezone.utc)), bbox=(28.1102397, 36.034105, 29.3584675, 37.041254), geometry={'type': 'Polygon', 'coordinates': [[[28.1244855, 37.041254], [29.3584675, 37.0231378], [29.3286142, 36.034105], [28.1102397, 36.0515828], [28.1244855, 37.041254]]]}, assets=[AssetVibe(type='image/tiff', id='4c1129a4-92e3-4b4f-a3da-86086b424f6b', path_or_url='/root/.cache/farmvibes-ai/data/assets/4c1129a4-92e3-4b4f-a3da-86086b424f6b/4c1129a4-92e3-4b4f-a3da-86086b424f6b.tif', _is_local=True, _local_path='/root/.cache/farmvibes-ai/data/assets/4c1129a4-92e3-4b4f-a3da-86086b424f6b/4c1129a4-92e3-4b4f-a3da-86086b424f6b.tif')], product_name='S2B_MSIL2A_20230514T084559_N0509_R107_T35SPA_20230514T212753', orbit_number=32308, relative_orbit_number=107, orbit_direction='descending', platform='2B', extra_info={}, tile_id='35SPA', processing_level='L2A', bands={'B01': 0, 'B02': 1, 'B03': 2, 'B04': 3, 'B05': 4, 'B06': 5, 'B07': 6, 'B08': 7, 'B8A': 8, 'B09': 9, 'B11': 10, 'B12': 11, 'A': 0, 'B': 1, 'G': 2, 'R': 3, 'RE1': 4, 'RE2': 5, 'RE3': 6, 'N': 7, 'N2': 8, 'WV': 9, 'S1': 10, 'S2': 11})], 'clipped_raster': [Sentinel2Raster(id='40e8d78c0c4f130644037c26cd84295ddf63979fcbfd798378a6adb63461ee3a', time_range=(datetime.datetime(2023, 5, 14, 8, 45, 59, 24000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 14, 8, 45, 59, 24000, tzinfo=datetime.timezone.utc)), bbox=(28.460218837306, 36.996874571809, 28.465741620962, 37.002368347424), geometry={'type': 'Polygon', 'coordinates': [[[28.461256880988, 37.002353698968], [28.461270192782, 37.002217852155], [28.461304962248, 37.002077721002], [28.4615593751, 37.001707837318], [28.461854021088, 37.001227635167], [28.462121844985, 37.000738861637], [28.462372384615, 37.000197536428], [28.462186697837, 37.000216815342], [28.462136721843, 36.999435231561], [28.462137330214, 36.999354287498], [28.462419570531, 36.999344033535], [28.462777521071, 36.999327809858], [28.463488057733, 36.999282509729], [28.463584891951, 36.999256303545], [28.463593213273, 36.999189396888], [28.463470710814, 36.999135157542], [28.463436422481, 36.999091712936], [28.463364583222, 36.999001141338], [28.463226269121, 36.998802860693], [28.462975033056, 36.998851970367], [28.46272379699, 36.998913932839], [28.462408187908, 36.998973753125], [28.462173045096, 36.999016436284], [28.462119665657, 36.998710094386], [28.462092975937, 36.998556922974], [28.462087677704, 36.998525322292], [28.46208506168, 36.998429457077], [28.462103614625, 36.998409192001], [28.462100709897, 36.998361078929], [28.462089536025, 36.998335543817], [28.462102056996, 36.998275904943], [28.462813744447, 36.998195185914], [28.462983597642, 36.997858982071], [28.463126641792, 36.997823818595], [28.463275050359, 36.997799365951], [28.463376076733, 36.99779249505], [28.463471738689, 36.997783481979], [28.463564718436, 36.997791606265], [28.463614782838, 36.997808299227], [28.46369376565, 36.997976776448], [28.46364400243, 36.997995301974], [28.463005469397, 36.9983164264], [28.4630321242, 36.998359070012], [28.463338580278, 36.998794073551], [28.463390571169, 36.998905716128], [28.463464019732, 36.999017358542], [28.463529421669, 36.999088300273], [28.463637738949, 36.999116399307], [28.463901239751, 36.999140038574], [28.463945043675, 36.999137182394], [28.46398348318, 36.999125757687], [28.46425616345, 36.998995801559], [28.465528907044, 36.997874003575], [28.465626515475, 36.997724103538], [28.465639082412, 36.997567102558], [28.465635556096, 36.997382252904], [28.465731503873, 36.99696774849], [28.465741620962, 36.996874571809], [28.465467297286, 36.997021791625], [28.465407550331, 36.997061901725], [28.465304149676, 36.99714212186], [28.465252916488, 36.99714832452], [28.46515581453, 36.997203573572], [28.464810066995, 36.997440350499], [28.464426768534, 36.99773282316], [28.463865732572, 36.997830303554], [28.463560242316, 36.99768082479], [28.463399526396, 36.997722621601], [28.463222717221, 36.997730143655], [28.462885192127, 36.997805168523], [28.462617837707, 36.99786953139], [28.462388900697, 36.997839736677], [28.461650242516, 36.997619780542], [28.461163711983, 36.997468373519], [28.46104239523, 36.997416854851], [28.460974722656, 36.997382473598], [28.460844741928, 36.997369407785], [28.460576733845, 36.997850971641], [28.460417355227, 36.998097966185], [28.460518150884, 36.998115749104], [28.460282967764, 36.998439655015], [28.460241998668, 36.998599163899], [28.460251991543, 36.998696550295], [28.460304163801, 36.998895606991], [28.460340242805, 36.999064673299], [28.460349499719, 36.999242307747], [28.460391891792, 36.999318774571], [28.460484330393, 36.999423215469], [28.46056067574, 36.999574782863], [28.460648993418, 36.99977081113], [28.460675425068, 36.999920808147], [28.460653186515, 37.000079422488], [28.460437353015, 37.000419603572], [28.460218837306, 37.000764067306], [28.460344548438, 37.000901953865], [28.46044495493, 37.000994459926], [28.460529268167, 37.001095534182], [28.460769961594, 37.001469840944], [28.460906232181, 37.001936231936], [28.461155155547, 37.002368347424], [28.461256880988, 37.002353698968]]]}, assets=[AssetVibe(type='image/tiff', id='4c1129a4-92e3-4b4f-a3da-86086b424f6b', path_or_url='/root/.cache/farmvibes-ai/data/assets/4c1129a4-92e3-4b4f-a3da-86086b424f6b/4c1129a4-92e3-4b4f-a3da-86086b424f6b.tif', _is_local=True, _local_path='/root/.cache/farmvibes-ai/data/assets/4c1129a4-92e3-4b4f-a3da-86086b424f6b/4c1129a4-92e3-4b4f-a3da-86086b424f6b.tif')], product_name='S2B_MSIL2A_20230514T084559_N0509_R107_T35SPA_20230514T212753', orbit_number=32308, relative_orbit_number=107, orbit_direction='descending', platform='2B', extra_info={}, tile_id='35SPA', processing_level='L2A', bands={'B01': 0, 'B02': 1, 'B03': 2, 'B04': 3, 'B05': 4, 'B06': 5, 'B07': 6, 'B08': 7, 'B8A': 8, 'B09': 9, 'B11': 10, 'B12': 11, 'A': 0, 'B': 1, 'G': 2, 'R': 3, 'RE1': 4, 'RE2': 5, 'RE3': 6, 'N': 7, 'N2': 8, 'WV': 9, 'S1': 10, 'S2': 11})]}
`

**Comment by robertomest** [comment]
Hello @guvenakcoban. This workflow only changes the metadata in the `Raster` and reuses the asset, so the actual file is not changed. This is because you can actually read portions of the tiff file without loading everything to memory. Here is an example of how you might do that:

```python
import geopandas as gpd
import rasterio
from rasterio.mask import mask
from shapely import geometry as shpg

# Assuming you have an output variable that contains the output of the op
clipped_raster = output["clipper_raster"]
geom = shpg.shape(clipped_raster.geometry)
with rasterio.open(output["clipped_raster"].raster_asset.path_or_url) as src:
    # Project our geometry into the raster CRS
    # I'm using the envelope here to have a square (avoid nodata values)
    # You could use your geometry directly if you prefer
    proj_geom = gpd.GeoSeries(geom, crs="epsg:4326").to_crs(src.crs).iloc[0].envelope
    bands_array = mask(src, [geometry], crop=True, **kwargs)[0]
```

You can also see an example of this in the Sentinel/SpaceEye notebook available [in the repo](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/sentinel/sentinel_spaceeye.ipynb).

Let me know if this helps.

**Comment by rafaspadilha** [comment]
Closing this issue for now. @guvenakcoban, feel free to reopen it if you still have any issues.
