### ISSUE TITLE
Indice's status stays as 'queued' when run for 109 indices

### ISSUE THREAD

**Issue by click2cloud-Nagaraj** [microsoft/farmvibes-ai#112]
Hello team,
While running the workflow to compute 109 indices, spaceeye is computed as expected but no other indice comes into running and remain as queued.
And we tried cancelling this workflow, which had no effect on the workflow and it stays in running with the timer clicking.

PFA log files, which include :
1. Orchestrator logs.
2. Worker logs.
3. Screenshot for the workflow progress.

[109_indices_logs.zip](https://github.com/microsoft/farmvibes-ai/files/12000655/109_indices_logs.zip)

**Comment by robertomest** [comment]
Hello @click2cloud-Nagaraj. I have been investigating issues with the status update of very large workflows like this. We have improved our implementation and the cluster should handle scenarios like this much better. The fix will be available on our next release.

**Comment by rafaspadilha** [comment]
Hi, @click2cloud-Nagaraj. Are you still experiencing this issue?

**Comment by rafaspadilha** [comment]
Closing this issue for now. @click2cloud-Nagaraj, feel free to reopen it if the problem persists.
