### ISSUE TITLE
Question: Interpretation of outputs in crop_segmentation.ipynb notebook

### ISSUE THREAD

**Issue by jardabezdek** [microsoft/farmvibes-ai#12]
I cannot understand the purpose of the [crop_segmentation.ipynb](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/crop_segmentation/crop_segmentation.ipynb) notebook. I can understand it shows some differences of the lands, as is visible in the last cell. However, I do not understand how the heat map in the last cell output can be interpreted... 🤔  What does the yellow colour mean? And what does the blue colour mean? Can you help me with that, please?

Thank you!

**EDIT**

I am sorry, I am not able to add any further info to the issue (assignees, label, project, ...).

**Comment by rafaspadilha** [comment]
Hi, @jardabezdek. Thank you for raising this question.

In that example notebook, our goal is to train a crop land segmentation model. Given a set of Sentinel-2 images taken throughout a year, we want to estimate where the regions with crops are.

The maps that you see in the last cell show the prediction of the network (top image) and the ground-truth crop land map (bottom image). These are probability heatmaps, i.e., high values (yellow color) mean that region/pixel was assigned as crop land by the model, whereas low values (blue color) represent regions without crop areas. 

We will improve on the description and labels of both maps for the next release.

**Comment by renatolfc** [comment]
This was implemented in #14, specifically in https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/crop_segmentation/04_inference.ipynb. I'm closing this issue.

@jardabezdek, please feel free to reopen if you think this could be further improved.
