### ISSUE TITLE
API connection over local network

### ISSUE THREAD

**Issue by poysh** [microsoft/farmvibes-ai#122]
Dear Farmvibes-Team,

I am trying to access my farmvibes-ai (machine A) installation over the local network from a different machine (machine B), but it seems it is only available on the local machine. Is there any way to open or bridge the API port so I can run the vibes_core client on another machine on the same network?

**Comment by poysh** [comment]
Hey @py5gol, 
thank you so much, after some initial setup issues I finally managed to test run the new cluster over the network 🥳 
![image](https://github.com/microsoft/farmvibes-ai/assets/10188657/0899a9b5-046b-42a4-bfc9-db99c5f9ce35)
One follow up question regarding this. The raster output from the run is on the cluster machine A while the notebook calls the `raster_asset.url` points to machine B where the notebook is running. Any easy possibity to fix this or should I just put it on a shared drive and grab with based on the run id?

**Comment by rafaspadilha** [comment]
Hi, @poysh. Sorry for the long delay in the reply. We currently do not have an easy fix for this. Having a shared drive seems the easiest in your scenario. An alternative would be uploading the assets to a blob storage, from which you could access from the other machine.
