### ISSUE TITLE
Downloads from Sentinel Fail

### ISSUE THREAD

**Issue by shenoy10** [microsoft/farmvibes-ai#124]
Hi,

I'm looking to download a dataset of satellite imagery using the Farmvibes API platform. I seem to have failing downloads. When I run run.reason, it seems to be a key error, any insights into this issue?

failed getting secret with key pc-sub-key from secret store kubernetes: secrets “pc-sub-key” not found

I am currently trying to use the public api key.

**Comment by rafaspadilha** [comment]
Hi, @shenoy10. Thank you for using FarmVibes.AI. 

It seems that you have not added your PlanetaryComputer API Key to the cluster, or you have added it with a different key name (and the workflow is expecting "pc-sub-key"). You can add a new secret by following [the instructions in our documentation page](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/SECRETS.html).

An alternative would be to [pass your key as a workflow parameter](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/WORKFLOWS.html#workflow-parameters) directly when calling `client.run()` method.

Could you provide a code snippet of how you are calling your workflow and which workflow you are trying to run?

**Comment by shenoy10** [comment]
Solved the issue. Added the proper key.
