### ISSUE TITLE
[Feature request] Out of the box support for NDRE, ReCI indices

### ISSUE THREAD

**Issue by Yaswanth-Tippireddy** [microsoft/farmvibes-ai#13]
Hi, for those who wish to use farm vibes to monitor the crop health in plantations /orchards, out of the box support for a few more indices will be helpful.

Normalized Difference Red-Edge Index 

Formula ==> NDRE = (NIR – RedEdge)/(NIR + RedEdge)

Red-Edge Chlorophyll Vegetation Index

Forumla ==>  ReCI = (NIR / RED) – 1

Refer this link for more technical details.

[https://www.hiphen-plant.com/vegetation-indices-chlorophyll/3612/#:~:text=Chlorophyll%20Index%20(CI)&text=The%20red%2Dedge%20band%20is,bands%20and%20the%20NIR%20band.]

**Comment by robertomest** [comment]
Hello, @Yaswanth-Tippireddy. The indices have been added on our latest release #14.
