### ISSUE TITLE
Unable to access REST API documentation. 

### ISSUE THREAD

**Issue by nitinya9av** [microsoft/farmvibes-ai#131]
I was unable to access REST API documentation on `http://localhost:30000/v0/docs` it is showing failed to load API definition.

 ![283993089-92f4e134-a80c-4975-801c-6ee3c6fbee4d.png](https://github.com/microsoft/farmvibes-ai/assets/58939117/36f1bc79-cf03-44b1-8c08-237fa2bef6b7)

**Comment by rafaspadilha** [comment]
Hi, @nitinya9av. Thanks for raising this issue. It seems like we are having some errors with pydantic that is causing the rest-api to not properly show the documentation. We are investigating this and there will be a fix for the next release.

In the meantime, I suggest you use our Python client to interact with FarmVibes.AI cluster. Please, refer to our [documentation page for a guide on the client's functionalities](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/CLIENT.html), as well as the [complete documentation of the client module](https://microsoft.github.io/farmvibes-ai/docfiles/code/vibe_core_client/client.html#vibe_core.client.FarmvibesAiClient).

**Comment by Tejashreenk** [comment]
Is this issue solved? I am facing this same issue.

**Comment by Tejashreenk** [comment]
Is this issue solved? I am facing this same issue.

**Comment by rafaspadilha** [comment]
Hi, @Tejashreenk. We fixed this issue internally and a PR addressing it will be coming in the next few days.
Thanks for your patience.

**Comment by rafaspadilha** [comment]
Hi, @nitinya9av and @Tejashreenk. We just merged a new PR that fix the issue with the REST API documentation. Could you please update your clusters and let us know if the problem was fixed on your end?

**Comment by Tejashreenk** [comment]
Thanks Rafael,
I’ll check it out by the end of the day or tomorrow and let you know.

Regards
Tejashree Khedkar

**Comment by nitinya9av** [comment]
Hello @rafaspadilha . When I attempt to update the cluster using command `farmvibes-ai local update`, the terminal displays an error: `farmvibes-ai: command not found`. Consequently, I am trying to update the software dependencies by executing the following commands:
`bash ./resources/vm/setup_farmvibes_ai_vm.sh`
`pip install ./src/vibe_core`
However, I suspect that the vibe_core library installation might not be successful.
```
beats@beats-virtual-machine:~/farmvibes-ai$ pip install ./src/vibe_core
Defaulting to user installation because normal site-packages is not writeable
Processing ./src/vibe_core
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=961 sha256=73076188d547310f7d2683f83f5c637a2538491a54fd6eef6b866a5cdf1b3fc0
  Stored in directory: /tmp/pip-ephem-wheel-cache-f935xwfp/wheels/e0/d7/74/42347243f94985706751b2646632dae6a1159bc354a964901c
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
beats@beats-virtual-machine:~/farmvibes-ai$ farmvibes-ai local setup
farmvibes-ai: command not found

```

**Comment by nitinya9av** [comment]
Hello @rafaspadilha . After updating the **Farmvibes-ai cluster** `farmvibes-ai local update` and performing a local update, I can now successfully access the **REST API Documentation** Page on the Farmvibes-ai client at `http://127.0.0.1:31108/v0/docs`.

![Screenshot from 2024-02-11 14-45-04](https://github.com/microsoft/farmvibes-ai/assets/58939117/9a484704-0225-43bc-bce4-81f8de7738e3)

**Comment by rafaspadilha** [comment]
Awesome. I'm closing this issue for now. Please, folks, feel free to reopen it if you have any more trouble with the REST API docs.
