### ISSUE TITLE
Error installing env.yaml file via Conda

### ISSUE THREAD

**Issue by chetan2309** [microsoft/farmvibes-ai#141]
@renatolfc 

System details  - 

 - Running this command on Azure Ubuntu VM 20.04.6 LTS
 - Conda latest version

I have been tinkering with farmvibes for last 2-3 days, Since I don’t have a UNIX based machine, I ended up setting a
 
•	Azure VM
•	And since local setup was [giving error](https://protect-eu.mimecast.com/s/2tunCQOQ2s4l69MsMVj8o?domain=github.com) I setup an AKS cluster.
 
Finally, I was able to run hello world workflow of farmvibes successfully on a AKS cluster. 😊
 
My interest and intentions on farmvibes are primarily from ADMA perspective to start off with. I am running into a few errors while trying to setup/create by executing one of the conda commands. The Shell just stays there for eternity 😊 Tried this at least 5 times.

This remains stuck at this screen. Is there any way I can see logs of this to check what's happening?

![image](https://github.com/microsoft/farmvibes-ai/assets/539289/9aa820a1-93e1-44a9-98c5-4c47c93155ad)

This doesn't happen only for installing this env file. It happens if I pick any other notebook env file also. Happening across the board.

**Comment by m0828257** [comment]
I have the same problem when used the crop_env.yaml file. I see the las update was 2 years ago.

**Comment by gregcode123** [comment]
I'm having the same problem...
In my case, creating the environment for deepmc notebooks takes for ever... And at some point, it freezes the Ubuntu 20.04 box.

Question; if I use the Azure AKS cluster to run all the heavy processes, do I still need to create the environments? How is the process split in this case? I guess the heavy side of the process will be ran in the AKS cluster, so why I still need the environment? (sorry for my ignorance on this subject)

Thanks in advance!
Greg

**Comment by brsilvarec** [comment]
Hi Folks,

Thank you for bringing up this issue. I am currently investigating it and will provide a solution soon.

In response to @gregcode123's question,

The local environment `env.yaml` is crucial for processing and utilizing the data provided and required by FarmVibes. For example, the `vibe_core` package is needed to use the FarmVibes.AI client, which makes calls to the FarmVibes.AI cluster. Furthermore, `rasterio`, `xarray`, and `cartopy` are important packages for consuming and loading data from output rasters (FarmVibes.AI assets).

**Comment by brsilvarec** [comment]
Please consider using [micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) instead of conda. We have tested the environment creation process and it typically took around 2-3 minutes to finish.

The command for creating the environment should be:

```bash
micromamba  env create -f env.yaml  
micromamba activate farmvibes-ai  

```
Please let us know if this works for you. The updated documentation will be ready by the time of the next release.

**Comment by gregcode123** [comment]
Hello @brsilvarec 

I tried this; 
$ micromamba env create -f deepmc_env.yaml
but I get following errors:

```
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ python 3.8.*  is installable with the potential options
    │  ├─ python [3.8.0|3.8.1|...|3.8.8], which can be installed;
    │  ├─ python [3.8.0|3.8.1] would require
    │  │  └─ python_abi * *_cp38, which can be installed;
    │  └─ python [3.8.10|3.8.12|...|3.8.8] would require
    │     └─ python_abi 3.8.* *_cp38, which can be installed;
    ├─ pytorch ~=1.12.1  is installable with the potential options
    │  ├─ pytorch [1.10.2|1.11.0|1.12.1] would require
    │  │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
    │  ├─ pytorch [1.10.2|1.11.0|1.12.1] would require
    │  │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
    │  ├─ pytorch [1.10.2|1.11.0|1.12.1] would require
    │  │  ├─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
    │  │  └─ python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;
    │  ├─ pytorch [1.10.2|1.11.0|1.12.1] would require
    │  │  ├─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
    │  │  └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
    │  ├─ pytorch [1.10.2|1.11.0|1.12.1] would require
    │  │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
    │  ├─ pytorch [1.11.0|1.12.1] would require
    │  │  ├─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
    │  │  └─ python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
    │  ├─ pytorch [1.11.0|1.12.1] would require
    │  │  └─ __cuda, which is missing on the system;
    │  └─ pytorch 1.12.1, which can be installed;
    └─ torchvision ~=0.11.3  is not installable because there are no viable options
       ├─ torchvision 0.11.3 would require
       │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  └─ pytorch 1.10.2  but there are no viable options
       │     ├─ pytorch 1.10.2 would require
       │     │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch 1.10.2 conflicts with any installable versions previously reported;
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     └─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       ├─ torchvision 0.11.3 would require
       │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  ├─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
       │  └─ python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  └─ pytorch [* cpu*|>=1.10.2,<1.11.0a0 ] but there are no viable options
       │     ├─ pytorch 1.10.2, which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch 1.10.2 conflicts with any installable versions previously reported;
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     └─ pytorch * conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  └─ pytorch [* cpu*|>=1.11.0,<1.12.0a0 ] but there are no viable options
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.10.2|1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch 1.11.0 conflicts with any installable versions previously reported;
       │     ├─ pytorch [1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     ├─ pytorch [1.11.0|1.12.1], which cannot be installed (as previously explained);
       │     └─ pytorch * conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  ├─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
       │  └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
       ├─ torchvision 0.11.3 would require
       │  └─ pytorch * cuda*, which conflicts with any installable versions previously reported;
       └─ torchvision 0.11.3 would require
          └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs

```

**Comment by chetan2309** [comment]
@gregcode123 - I faced this too. you can resolve this by using ->  pytorch~=1.10.2 in the file on line no - 10. This will help resolve the dependencies.

**Comment by gregcode123** [comment]
Thanks @chetan2309 
I was able to create the environment.
However, jupyter notebook does not work properly (the browser opens a blank page... and nothing is being displayed...)
Not sure what else to check...

**Comment by gregcode123** [comment]
Thanks @chetan2309 
I was able to build the environment, but using the deepmc notebook gives an import error:

ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports'

I changed python=3.9 and pytorch=1.10.2

Also;
torchvision=0.11.3

Any recommendation?
Thanks

**Comment by chetan2309** [comment]
> Please consider using [micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) instead of conda. We have tested the environment creation process and it typically took around 2-3 minutes to finish.
> 
> The command for creating the environment should be:
> 
> ```shell
> micromamba  env create -f env.yaml  
> micromamba activate farmvibes-ai  
> ```
> 
> Please let us know if this works for you. The updated documentation will be ready by the time of the next release.

@brsilvarec @rafaspadilha - I was able to resolve it using Mamba, I haven't tried micromamba. But I am sure it will work too.

**Comment by rafaspadilha** [comment]
Closing the issue for now, folks. Feel free to reopen or create a new one if you have additional doubts.
