### ISSUE TITLE
Error running basemap_segmentation workflow - sam_inference failed

### ISSUE THREAD

**Issue by RMNT** [microsoft/farmvibes-ai#145]
### In which step did you encounter the bug?

Workflow execution

### Are you using a local or a remote (AKS) FarmVibes.AI cluster?

Local cluster

### Bug description

I am new to using bingmaps so it might be a mistake on my part. 

In the website I created a key, copied it and pasted to the BING-MAPS_API_KEY constant. I did not change anything else in the code. After running the code I get this:

```
                  🌎 FarmVibes.AI 🌍 farm_ai/segmentation/segment_basemap 🌏 
                                 Run name: Basemap segmentation
                         Run id: 4e232c4a-d514-4b34-9987-eb2647fa7b13
                                       Run status: failed
                                     Run duration: 00:00:22

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Task Name                 ┃ Status ┃ Start and End Time ┃ Duration ┃ Progress   
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ sam_inference                              │failed│...│...│00:00:17│ ━━━━━━━━━━━━━━━━━━━━  0/1    │
│ basemap_download.merge                     │done│...│...│00:00:00│  ━━━━━━━━━━━━━━━━━━━━  1/1     │
│ basemap_download.to_sequence               │done│...│...│00:00:00│  ━━━━━━━━━━━━━━━━━━━━  1/1     │
│ ingest_points.download                     │done│...│...│00:00:01│  ━━━━━━━━━━━━━━━━━━━━  1/1     │
│ basemap_download.basemap_download.download │done│...│...│00:00:00│  ━━━━━━━━━━━━━━━━━━━━  25/25   │
│ ingest_points.unpack                       │done│...│...│00:00:01│  ━━━━━━━━━━━━━━━━━━━━  1/1     │
│ basemap_download.basemap_download.list     │done│...│...│00:00:03│  ━━━━━━━━━━━━━━━━━━━━  1/1     │
└───────────────────────────────────────────────────────────────────────────────────────────────────┘
```
Key details:
```
Key type: Basic / Dev/Test
Created date: 02/02/2024
Expiration date: None
Key Status: Enabled
Security Enabled: No
```

What may I be doing wrong?

**Comment by rafaspadilha** [comment]
Hi, @RMNT. Thanks for raising the issue. It seems that nothing is wrong with the BingMaps steps of the workflow, but rather to the segmentation part. 

Please, could you provide the content of the `reason` attribute of your run object?

```python
client = get_default_vibe_client()

run = client.run(....)

print(run.reason)
```

**Comment by rafaspadilha** [comment]
We noticed the script that downloads the SAM models, trace them to ONNX, and export to FarmVibes cluster is missing from the repo (as reported in #153). Your issue might be related to this and the `reason` might confirm this. If this is the case, you can expect them to be included in the next release. Thank you for your patience.

**Comment by rafaspadilha** [comment]
@RMNT PR #157 adds the missing script and you should be able to run the SAM workflows and notebooks. 
Thank you for your patience.

Please, let me know if you are able to test it and if any issues come up.

**Comment by rafaspadilha** [comment]
Closing this issue for now. @RMNT, feel free to reopen it if you encounter any more issues.
