### ISSUE TITLE
Unable to run the irrigation_classification notebook

### ISSUE THREAD

**Issue by ZoloKiala** [microsoft/farmvibes-ai#156]
### In which step did you encounter the bug?

Notebook execution

### Are you using a local or a remote (AKS) FarmVibes.AI cluster?

Local cluster

### Bug description

I'm trying to run the Irrigation Classification Notebook, but I'm getting the following error:

![image](https://github.com/microsoft/farmvibes-ai/assets/65705483/21e8b63c-0930-4920-9dbe-ce8d30fc23e4)

When I run " run.reason", the log file looks as follows: 
"RuntimeError: Failed to run op stack_landsat_bands in workflow run id cb40bb24-ebf0-4f82-96af-c87fa9df479c for input with message id 00-cb40bb24ebf04f8296afc87fa9df479c-7f94920eace13cef-01. Error description: <class 'RuntimeError'>:  self._exception\npebble.common.ProcessExpired: Abnormal termination\n."

I also tried to change the buffer size to download a smaller image, but I'm getting the same error.

Can you also advise on how to customise the workflow for my study area ? I get see that the model was calibrated using training samples collected in a field in Nebraska. How do I use my own model ?

**Comment by edrodrigues-ag** [comment]
Hi @ZoloKiala , it looks like you have run out-of-memory. If you are running this in a VM, you are able to see OOM messages with `dmesg` (you may need to run this as root). This specific model is a simple logistic regression with parameters you can adjust (please see the parameters in the https://microsoft.github.io/farmvibes-ai/docfiles/markdown/workflow_yaml/farm_ai/water/irrigation_classification.html ). If you want more sophisticated models, you can express them as Onnx files (see an example as in https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/crop_cycles/crop_cycles.ipynb). Please let us know if you have any further question.

**Comment by ZoloKiala** [comment]
@edrodrigues-ag Thanks for your prompt reply. I'm using WSL. My computer has 10 processing cores (I think it's good enough). Should I move to a VM ?

I will try to more sophisticated models as suggested.

**Comment by ZoloKiala** [comment]
I increased the memory amount allocated to WSL. It's working now. Thank you very much!
