### ISSUE TITLE
farmvibes-ai local setup

### ISSUE THREAD

**Issue by marias65** [microsoft/farmvibes-ai#160]
Your country: USA
Your contact info to reach out to you: msbksan@iastate.edu
What is your scenario for using FarmVibes.AI?: I am a computer science college student trying to implement it on my own for a research project I am a part of. My goal is to use the segmentation notebooks to segment surrounding farmland.

I am just trying to set up farmvibes on a local machine by following the quickstart instructions but when I try to run the `farmvibes-ai local setup` I get a message saying "farmvibes-ai: command not found". I've included a screenshot because I am fairly sure that I am in the correct folder and I have downloaded all the dependencies without a problem so I am not sure what is wrong? Some help would be great!

![GetImage](https://github.com/microsoft/farmvibes-ai/assets/114122115/140a73ae-441c-4f5b-8a15-ca5949a8b3c6)

**Comment by marias65** [comment]
Yes, I did run `pip install ./src/vibe_core` before trying to run the setup command. I tried it again just in case and this was the output. Is this what it is supposed to look like?

![GetImage](https://github.com/microsoft/farmvibes-ai/assets/114122115/357ff13a-194e-4cba-983b-2af6149b992f)

**Comment by rafaspadilha** [comment]
Please, could you run `pip install --upgrade pip` and then retry installing `vibe_core`?

**Comment by renatolfc** [comment]
From the first screenshot you shared, it seems you don’t have a virtualenv activated.

This means pip probably used a local bin directory to install farmvibes-ai in.

Can you try running `~/.local/bin/farmvibes-ai` instead of plain `farmvibes-ai` when running farmvibes commands?

**Comment by marias65** [comment]
That seems to have worked!! Thank you so much!

**Comment by renatolfc** [comment]
Nice!

If you’re using bash, you might want to add that directory to your path by appending a line with `export PATH=$PATH:$HOME/.local/.bin` to your `~/.bashrc` file.
