### ISSUE TITLE
Irrigation classification notebook training data

### ISSUE THREAD

**Issue by ajinkyapol** [microsoft/farmvibes-ai#162]
### Topic

Workflow

I am working on irrigation classification notebook. when i run it on different area of interest it does not work, which is obvious because the model coefficients and intercept are callibrated for Nebraska for the year 2015. Could you please provide following things:
1.  training data you used to train this model.
2.  How to collect training data for any user defined AOI.
3. And using this training data how to train model in 'farm_ai/water/irrigation_classification' workflow.

**Comment by rafaspadilha** [comment]
Hi, @ajinkyapol. Thanks for raising this question.

Unfortunately, the dataset used to train the logistic regression in that workflow is not public. The model was trained with a similar data source setup as described in [Application of Remote Sensing Technology in Water Resources Management](https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1142&context=civilengdiss).

If you have data available in our region of interest, you can train the model with the same inputs described in the notebook and use the workflow for inference.
