### ISSUE TITLE
Having Problem in VM Setup.

### ISSUE THREAD

**Issue by nitinya9av** [microsoft/farmvibes-ai#18]
I am trying to set up VM for farmvibes.ai with docker on Microsoft azure but don,t understand the setup guide.
What does this point mean? (in the picture below)
![Screenshot (173)](https://user-images.githubusercontent.com/58939117/203111470-b01e5c38-77a1-4cf1-8912-c0dc0ba77ad2.png)
my terminal shows this error
![Screenshot (174)](https://user-images.githubusercontent.com/58939117/203112160-138cc3c9-49fc-4bab-94f2-9b16dccb34c0.png)

**Comment by brsilvarec** [comment]
Hi there @nitinya9av,

Thanks for sharing this. I believe you need to create the SSH public key. As stated in the documentation you need to create it using the `ssh-keygen` command and use the default options. Please, see the following figure that shows how to proceed. After creating the public key and logging into azure, you should be able to create the VM.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/7769154/203127178-495e9555-afc0-40a8-9ba6-33ab3cddba97.png">

**Comment by brsilvarec** [comment]
Please, be advised this will create a SSH key that will be only accessible while you have the container is running. If you loose the container your will have no way to connect to your VM.

I recommend you use a more stable platform like a Linux machine (WSL can be an option) to create the FarmVibes.AI vm.

**Comment by brsilvarec** [comment]
Please, be advised this will create a SSH key that will be only accessible while you have the container is running. If you loose the container your will have no way to connect to your VM.

I recommend you use a more stable platform like a Linux machine (WSL can be an option) to create the FarmVibes.AI vm.

**Comment by brsilvarec** [comment]
You also need to clone the repository and execute the azure deployment command inside the `farmvibes-ai` folder.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/7769154/203131028-8d84ac45-ea2e-4cfe-bbb8-e66e97ef8031.png">

My Recommendation is to do the following.

1. Use a more stable Linux environment to deploy the FarmVibes.AI VM.
2. Once you create/access this environment, issue the `ssh-keygen` command. 
3. Clone the repository and enter the folder.
4. Log into the azure cli using a valid subscription.
5. Create the VM.

Please, let me know if this worked for you.

**Comment by brsilvarec** [comment]
If you really want to use a container to create the VM, you can use a [volume](https://docs.docker.com/storage/volumes/) to persist the SSH key in your windows host. In the following example, I created a folder that will persist the ssh keys (`C:\Users\brunosilva\Documents\ssh`). Please, replace this folder with a valid folder in your system.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/7769154/203141894-45c215d2-25a5-4970-9b39-d68235b4f6de.png">

This command created the container, generated the SSH key, and killed the container. 

Observe when I created the container again, my SSH public key was there. Without the volume, the SSH public key would not be there.

**Comment by nitinya9av** [comment]
I am trying to create volume but it shows an error!! 
I am using WSL Ubuntu 20.04 (as you recommend) 
[Screenshot (175)](https://user-images.githubusercontent.com/58939117/203539575-0814adab-5880-4a26-bbc4-81b2f47adca4.png)

**Comment by nitinya9av** [comment]
I am trying to create volume but it shows an error!!
I am using WSL Ubuntu 20.04 (as you recommend)
![Screenshot (175)](https://user-images.githubusercontent.com/58939117/203540301-cb95f1e0-518e-44d7-8d85-6a615c1d8055.png)

**Comment by nitinya9av** [comment]
I am using WSL Ubuntu 20.04(as you recommended) but while running this volume command get an error.
![Screenshot (176)](https://user-images.githubusercontent.com/58939117/203540723-7c2545b2-a390-4b2b-b777-f52edf1a8cb2.png)

**Comment by brsilvarec** [comment]
If your running on WSL there is no need to add the volume @nitinya9av. Volume creation is only required if you are using a windows machine. 

Please try consider installing azure cli on your WSL `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` should be fine. After doing that, proceed as explained here.

https://github.com/microsoft/farmvibes-ai/issues/18#issuecomment-1322480673

Please let me know if this worked or not ... I am glad to help

**Comment by nitinya9av** [comment]
Now, I am using WSL ubuntu 20.04 (without the docker container) as you recommend and after following 4 steps that you mentioned

 My Recommendation is to do the following.
 1. Use a more stable Linux environment to deploy the FarmVibes.AI VM.
 2. Once you create/access this environment, issue the `ssh-keygen` command.
 3. Clone the repository and enter the folder.> 4. Log into the azure cli using a valid subscription.
 5. Create the VM using the command you pasted.

but at step 5 I am getting this
![Screenshot (177)](https://user-images.githubusercontent.com/58939117/203609487-cbf8a745-1463-4db7-a9c3-fe3d4f268bdf.png)

**Comment by brsilvarec** [comment]
Thanks for your quick response. 

It seems your bicep was not installed properly. Can you run this command?

`az bicep upgrade`

If this does not work, please consider [reinstalling azure cli](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt).

**Comment by nitinya9av** [comment]
Hi @brsilvarec 
First I run az bicep upgrade command and get this
![Screenshot (179)](https://user-images.githubusercontent.com/58939117/203616428-ca4fdad8-71ca-4c19-aefe-a09608d1a0a6.png)
then I reinstall azure cli with both methods and get the same.

**Comment by brsilvarec** [comment]
It seems there is something wrong with your azure cli installation. This kind of error usually happens when we try to execute some software in a wrong platform. 

According to your terminal screenshot you are using Ubuntu, then this should be the platform 
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

<img width="471" alt="image" src="https://user-images.githubusercontent.com/7769154/203657622-8dd51efe-c26c-4d28-baca-87742b572f4b.png">

My recommendation is to uninstall the azure cli at the end of pointed page and try again.

This is the expected behavior for a successful azure cli installation.

```bash
╰─➤  az bicep --help                                                                                                             2 ↵

Group
    az bicep : Bicep CLI command group.

Commands:
    build         : Build a Bicep file.
    decompile     : Attempt to decompile an ARM template file to a Bicep file.
    install       : Install Bicep CLI.
    list-versions : List out all available versions of Bicep CLI.
    publish       : Publish a bicep file to a remote module registry.
    uninstall     : Uninstall Bicep CLI.
    upgrade       : Upgrade Bicep CLI to the latest version.
    version       : Show the installed version of Bicep CLI.

To search AI knowledge base for examples, use: az find "az bicep"

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
```

**Comment by brsilvarec** [comment]
Please, also consider taking a looking at this troubleshooting page related to Azure CLI on WSL. https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#cli-fails-to-install-or-run-on-windows-subsystem-for-linux

**Comment by nitinya9av** [comment]
The Above problem is solved by first uninstalling bicep using the command az bicep uninstall and then reinstalling it.
but now, I have a new error in my azure quota I have an **azure for student subscription** which only allows 6 vCPUs is there any way that I can run farmvibes.ai on **6 vCPUs instead of 8 vCPUs**?
  
![Screenshot (180)](https://user-images.githubusercontent.com/58939117/203691549-0a5f5102-0db4-4ac0-a212-7a55b68d69a0.png)

**Comment by brsilvarec** [comment]
You can use this parameter after `encoded_script`.

**Comment by brsilvarec** [comment]
BTW, you can check out tutorial video showing how to set up the parameters for the FarmVibes.AI VM.

https://youtu.be/RNoA7ri2v5I?t=1811

**Comment by nitinya9av** [comment]
Thanks!! @brsilvarec 
This is for all whois have an azure student subscription you can use parameters vm_size=Standard_DS3_v2
VM setup is successful.
👌👍

**Comment by brsilvarec** [comment]
Thansk @nitinya9av
