### ISSUE TITLE
Workflow for Training Models

### ISSUE THREAD

**Issue by 12devsilva12** [microsoft/farmvibes-ai#20]
It seems like the default VM created in the VM setup does not have the ability to train models (i.e. has GPUs). Any recommendations on how to setup a VM to train models on Azure and how to have it interact with FarmVibes Cluster created with the default VM?

**Comment by rafaspadilha** [comment]
Hi, @12devsilva12. Thank you for raising this question.

When following the [VM setup guide](https://github.com/microsoft/farmvibes-ai/blob/main/documentation/VM-SETUP.md), you are able to define the specs of your desired VM with the parameter `vm_size`.

```
az deployment group create --resource-group <resource_group> \
  --name <deployment_name> \
  --template-file  resources/vm/farmvibes_ai_vm.bicep \
  --parameters \
           ssh_public_key="$(cat ~/.ssh/id_rsa.pub)" \
           vm_suffix_name=<my_test_suffix> \
           encoded_script="$(cat resources/vm/setup_farmvibes_ai_vm.sh | gzip -9 | base64 -w0)" \
           vm_size=Standard_NC6s_v3
```

In the above example, I am using a `Standard_NC6s_v3` VM, which has 1 GPU. For a list of available VM sizes and their resources, please refer to [this link](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes). Specifically for GPU-enabled VMs, refer to [this page](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-gpu).

Another option would be to set up your training tasks in Azure Machine Learning. In this case, you can still create the FarmVibes.AI cluster in a VM without GPU, run your workflows, and then transfer the data to an AML compute instance for training. We have an [example notebook](https://github.com/microsoft/farmvibes-ai/blob/main/notebooks/crop_segmentation/03_aml_training.ipynb) that covers a similar scenario for training models for [Crop Land Segmentation](https://github.com/microsoft/farmvibes-ai/tree/main/notebooks/crop_segmentation).

**Comment by rafaspadilha** [comment]
Closing this issue. @12devsilva12 let us know if you had any issues changing the VM size.
