### ISSUE TITLE
How Can I Run Dockerfile-dev for development

### ISSUE THREAD

**Issue by Hi1805** [microsoft/farmvibes-ai#212]
### Topic

Documentation

### Ask away!

Thank  you for your development,

I want to run file Dockerfile-dev 
![Image](https://github.com/user-attachments/assets/5bffa7a1-7939-43ec-9a86-a74252214f28)

But have error, I guess i miss file enviroment for dev.

I want to run test 
![Image](https://github.com/user-attachments/assets/57b179e2-343f-4c8c-a684-fff755f3804f)

But i don't know, how it will work

**Comment by rafaspadilha** [comment]
Hi, @Hi1805. 

For setting up and running FarmVibes, please follow the instructions in our [QuickStart guide](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html). That will get a cluster up and running if you need to run workflows/operations.
 
We still don't have proper documentation for setting up a development environment and testing changes to ops and workflows. I will work on adding one soon.

My recommendation is the following steps:
- Make sure you have a FarmVibes.AI cluster up and running (see [QuickStart guide](https://microsoft.github.io/farmvibes-ai/docfiles/markdown/QUICKSTART.html))
- Set up a new conda environment
- Run the [setup_python_develop_env.sh](https://github.com/microsoft/farmvibes-ai/blob/dev/scripts/setup_python_develop_env.sh) script to install all the dev packages.
- Implement a new op or make changes to existing ops
- Test the code with `OpTester` class from [vibe_dev/testing/op_tester.py](https://github.com/microsoft/farmvibes-ai/blob/dev/src/vibe_dev/vibe_dev/testing/op_tester.py)
- Rebuild your worker with `make local-worker` from [Makefile](https://github.com/microsoft/farmvibes-ai/blob/dev/Makefile)

Let me know if you have any doubts.
I will add this to a documentation page.

**Comment by Hi1805** [comment]
Hi @rafaspadilha , Thank you for reply.

When i try setup [setup_python_develop_env.sh](https://github.com/microsoft/farmvibes-ai/blob/dev/scripts/setup_python_develop_env.sh)
I have problem
![Image](https://github.com/user-attachments/assets/6a6bc4e6-9ad2-43ba-9b7e-c41b1b7ca462)

![Image](https://github.com/user-attachments/assets/fa595a75-9e00-449a-9afb-351e1e0ab08a)

I think it is conflicting version python :((.

I try run file [vibe_dev/testing/op_tester.py](https://github.com/microsoft/farmvibes-ai/blob/dev/src/vibe_dev/vibe_dev/testing/op_tester.py).
I will be failed, because miss package 
![Image](https://github.com/user-attachments/assets/08e9a96c-374f-417b-a056-8e27c9f92918)
![Image](https://github.com/user-attachments/assets/2db2254d-4f4e-4a79-a5e4-068fd85cdfaa)

Could you please help, how i can run test op or workflow :(( ?

Many thanks

**Comment by Hi1805** [comment]
@rafaspadilha  Many thanks,
I change version python 3.8.
It's work fine

**Comment by Hi1805** [comment]
Hi sir @rafaspadilha,

I Run Pip check, i see conflict version package when i run `bash setup_python_develop_env.sh`

![Image](https://github.com/user-attachments/assets/5a588aa9-59ec-4439-9d23-f4f408629306)

![Image](https://github.com/user-attachments/assets/3d2bc90e-5397-4d9e-baa7-a2ba691ee06c)

Python: 3.8

Please help me check it :( ?

Many thanks
