### ISSUE TITLE
Workflows not terminating in AML compute

### ISSUE THREAD

**Issue by NicholasBerryman** [microsoft/farmvibes-ai#23]
This may be related to my [other issue](https://github.com/microsoft/farmvibes-ai/issues/17). If so, feel free to close this.

After following the quickstart guide to install the newest farmvibes version in an Azure ML compute, any workflow I try to run hangs indefinitely and with no error message. A screenshot is attached.

![farmvibes problem](https://user-images.githubusercontent.com/3523408/204456500-76377723-b466-4acd-92b2-de211adfe719.png)

**Comment by renatolfc** [comment]
This might be related, yes. I'm closing this in favor of the other issue. If this turns out to be a different issue, we can always reopen it. Thanks.
