### ISSUE TITLE
Unable to Execute Helloworld workflow

### ISSUE THREAD

**Issue by saqibzia-dev** [microsoft/farmvibes-ai#30]
I have set up a virtual machine on Azure using the official documentation and video provided by FarmVibes-AI on GitHub and Microsoft Research. The installation process was successful, but when I attempted to run the "hello world" workflow, I encountered a timeout error. Despite increasing the timeout to 300 seconds, the error persists. I have included screenshots of the issue for your reference.

![WhatsApp Image 2023-01-27 at 2 51 57 PM](https://user-images.githubusercontent.com/56071934/215059238-79509afa-b6b5-49e9-8a58-f6979af30bc3.jpeg)
![WhatsApp Image 2023-01-27 at 2 52 46 PM](https://user-images.githubusercontent.com/56071934/215059241-4f5bac84-bce5-4344-bf28-d61efec00d58.jpeg)
![WhatsApp Image 2023-01-27 at 2 50 55 PM](https://user-images.githubusercontent.com/56071934/215059249-e3ac407c-efd4-4dad-b07a-d11376b1b3e4.jpeg)

**Comment by renatolfc** [comment]
Hello @saqibzia-dev, we are in the process of updating our images, and you probably checked old a version of the code that's incompatible with the images currently in the container registry.

I have opened a pull request from the `from-devops-release-186` branch that should fix your issue. If you checkout the `from-devops-release-186` and update the `vibe_core` library, your error should be fixed.

I'm currently waiting for the PR to be reviewed. Once it gets accepted and merged, simply updating your local copy of the code and updating the `vibe_core` library should work.

I'm curious, what is the output of `curl http://192.168.49.2:30000/v0/runs/1fee593a-62c8-48dd-8304-6fa8027d9757`?
