### ISSUE TITLE
Error while setting up farmvibes on Azure VM

### ISSUE THREAD

**Issue by saqibzia-dev** [microsoft/farmvibes-ai#31]
I am getting following error while setting up farmvibes on Azure VM.When I run this command " **bash farmvibes-ai.sh setup**" I get
"**error: deployment "terravibes-worker" exceeded its progress deadline**"

Here is the log:
**Log:**
Status: Downloaded newer image for mcr.microsoft.com/farmai/terravibes/cache:prod
mcr.microsoft.com/farmai/terravibes/cache:prod
Installing redis in the cluster...
statefulset.apps/redis-replicas scaled
Installing rabbitmq in the cluster...
secret/rabbitmq-connection-string created
component.dapr.io/control-pubsub created
component.dapr.io/statestore created
service/terravibes-rest-api created
deployment.apps/terravibes-rest-api created
deployment.apps/terravibes-orchestrator created
deployment.apps/terravibes-worker created
deployment.apps/terravibes-cache created
component.dapr.io/control-pubsub unchanged
component.dapr.io/statestore unchanged
service/terravibes-rest-api unchanged
deployment.apps/terravibes-rest-api unchanged
deployment.apps/terravibes-orchestrator unchanged
deployment.apps/terravibes-worker unchanged
deployment.apps/terravibes-cache unchanged
deployment.apps/terravibes-rest-api condition met
deployment "terravibes-rest-api" successfully rolled out
deployment.apps/terravibes-orchestrator condition met
deployment "terravibes-orchestrator" successfully rolled out
error: timed out waiting for the condition on deployments/terravibes-worker
Waiting for deployment "terravibes-worker" rollout to finish: 0 of 3 updated replicas are available...
error: deployment "terravibes-worker" exceeded its progress deadline
deployment.apps/terravibes-cache condition met
deployment "terravibes-cache" successfully rolled out

Success!

FarmVibes.AI REST API is running at http://192.168.49.2:30000

**Comment by renatolfc** [comment]
Hello @saqibzia-dev, what is the output of `~/.config/farmvibes-ai/kubectl get pods`? If all pods are running, you should be good to go.

Tuning the amount of time we should wait for deployments is a bit difficult. On the one hand, we could choose to not wait at all, and expect that eventually all pods would be running. If we did that, running workflows immediately after installation would potentially fail.

On the other hand, we could increase our timeout, but that would make installation take even longer.

In general, if the pods show as running, you should be alright.

**Comment by saqibzia-dev** [comment]
Hello @renatolfc Thanks for the quick response. When I execute **"~/.config/farmvibes-ai/kubectl get pods"**. I get the following output. It seems like some terravibes workers are not running.
![pods-error (1)](https://user-images.githubusercontent.com/56071934/215136907-09391bd1-b82a-497f-848b-1c7eb0ffb181.png)
