### ISSUE TITLE
Failure to execute 's2.download' workflow task with time_range in January 2022

### ISSUE THREAD

**Issue by NicholasBerryman** [microsoft/farmvibes-ai#36]
The 's2.download' workflow task seems to fail consistently with `time_range` set to include at least January 2022. It seems to work if January is excluded. I have only confirmed this for a few locations in Western Australia, and can't say whether it happens in any other locations.

Failure details message is as follows:

```
's2.s2.download': RunDetails(start_time=datetime.datetime(2023, 2, 9, 9, 44, 4, 752908), submission_time=datetime.datetime(2023, 2, 9, 9, 44, 4, 705244), end_time=datetime.datetime(2023, 2, 9, 10, 24, 29, 832081), reason='RuntimeError: Received unsupported message header=MessageHeader(type=<MessageType.error: \'error\'>, run_id=UUID(\'29d110b7-0ee2-46e4-91ef-345753402cb7\'), id=\'00-29d110b70ee246e491ef345753402cb7-f04b837f0791e025-01\', parent_id=\'00-29d110b70ee246e491ef345753402cb7-1ac389aaff11fcb8-01\', version=\'1.0\', created_at=datetime.datetime(2023, 2, 9, 10, 24, 29, 824878)) content=ErrorContent(status=<OpStatusType.failed: \'failed\'>, ename="<class \'RuntimeError\'>", evalue=\'Traceback (most recent call last):\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 121, in run_op\
    return factory.build(spec).run(input)\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 111, in run\
    stac_results = self._call_validate_op(**{**items, **raw_items})\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 75, in _call_validate_op\
    results = self.callback(**kwargs)\
  File "/app/ops/download_sentinel2_from_pc/download_s2_pc.py", line 56, in download_product\
    asset_path = collection.download_asset(item.assets[k], self.tmp_dir.name)\
  File "/opt/conda/lib/python3.8/site-packages/vibe_lib/planetary_computer.py", line 109, in download_asset\
    raise RuntimeError(f"Failed asset {asset.href} after {MAX_RETRIES} retries.")\
RuntimeError: Failed asset https://sentinel2l2a01.blob.core.windows.net/sentinel2-l2/50/J/LM/2022/01/26/S2B_MSIL2A_20220126T021339_N0400_R060_T50JLM_20220211T070542.SAFE/GRANULE/L2A_T50JLM_A025540_20220126T021913/IMG_DATA/R10m/T50JLM_20220126T021339_B02_10m.tif after 5 retries.\
\', traceback=[\'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 306, in run_op_from_message\
    out = self.run_op_with_retry(content, message.run_id)\
\', \'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 404, in run_op_with_retry\
    raise RuntimeError("".join(ret.format()))\
\']). Aborting execution.', status='failed')
```

When attempting to visit the asset url in a browser, I get a 'ResourceNotFound' error.

Thanks in advance for the help!

**Comment by robertomest** [comment]
Hi @NicholasBerryman, thanks for the report. I investigated the issue and it seems that the data is missing from the Planetary Computer blob storage. I checked all products available in Jan 2022 for the tile 50JLM, and it seems that one product is missing bands `B02, B03, B04` (the RGB bands). This is the reason the workflow is failing. Here is the output of a quick script that checks all the assets:
```
Missing assets:
S2A_MSIL2A_20220101T021351_R060_T50JLM_20220101T234032: []
S2B_MSIL2A_20220106T021339_R060_T50JLM_20220107T065451: []
S2A_MSIL2A_20220111T021351_R060_T50JLM_20220112T040949: []
S2B_MSIL2A_20220116T021339_R060_T50JLM_20220116T170814: []
S2A_MSIL2A_20220121T021341_R060_T50JLM_20220121T224412: []
S2B_MSIL2A_20220126T021339_R060_T50JLM_20220211T070542: ['B02', 'B03', 'B04']
S2A_MSIL2A_20220131T021341_R060_T50JLM_20220216T131530: []
```
I think the simplest way to mitigate this issue for now is to split your workflow into two time ranges, excluding Jan 26th. We'll follow up with folks from the Planetary Computer and are discussing how we could mitigate this within FarmVibes.

You mentioned some regions in Western Australia, would you be able to check if all the regions fall in this same tile? This would allow us to verify if other tiles are also missing data. Alternatively, I could do a quick check if you are able to share the geometries.

**Comment by NicholasBerryman** [comment]
Thanks for looking into that! 
It does like look all locations I examined had at least one point in their geometry in the same sentinel tile. A few did also intersect adjacent tiles.

**Comment by NicholasBerryman** [comment]
Sorry. Just realised I pressed the wrong button when commenting before. I'll leave this open until you guys are happy that the issues on the Planetary Computer side are resolved.

**Comment by TomAugspurger** [comment]
Thanks for catching this. We've reprocessed the scene that was missing assets. [Here](https://planetarycomputer.microsoft.com/explore?c=115.5071%2C-30.3522&z=8.56&v=2&d=sentinel-2-l2a&s=false%3A%3A100%3A%3Atrue&ae=0&sr=desc&m=cql%3A822deae32e1e975a7205d67f5d69a933&r=Natural+color) is the new item (note that the item ID changed).
