### ISSUE TITLE
mc_forecast.ipynb herbie download error

### ISSUE THREAD

**Issue by ziwonSeo-lab** [microsoft/farmvibes-ai#39]
OS : Ubuntu 22.04.1 LTS

At mc_forecast.ipynb
https://blaylockbk.github.io/Herbie/_build/html/

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus),

and

forecast_ = Forecast(
                workflow_name=HERBIE_DOWNLOAD_WORKFLOW,
                geometry=STATION_GEOMETRY,
                time_range=time_range,
                parameters=parameters,
                )
run_list = forecast_.submit_download_request()
>>ConnectionError: HTTPConnectionPool(host='192.168.49.2', port=30000): Max retries exceeded with url: /v0/runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff1eea52c70>: Failed to establish a new connection: [Errno 110] Connection timed out')) 

how to fix??

**Comment by v-ngangarapu** [comment]
Thanks for contacting with the issues identified.

For 404 error, looks like the url got changed. Please try with below url 

https://blaylockbk.github.io/Herbie/
