### ISSUE TITLE
Sentinel-1 list task error for first half of 2022 in some locations

### ISSUE THREAD

**Issue by NicholasBerryman** [microsoft/farmvibes-ai#43]
When trying to run the SpaceEye workflow for a location near Esperance in Western Australia (bounding box centre point: `121.4734,-33.19117` ), I encountered the following error, terminating the workflow. 

This error did not occur when providing a date range of 2022-3-1 to 2022-12-31, though this only returned SpaceEye outputs for 2022-8-1 onwards.
The error seems to occur only when a date range fully contained by March and August of 2022 is specified at this tile.

```
'preprocess.s1.list': RunDetails(start_time=datetime.datetime(2023, 2, 15, 3, 27, 13, 915573), submission_time=datetime.datetime(2023, 2, 15, 3, 27, 13, 770448), end_time=datetime.datetime(2023, 2, 15, 3, 27, 26, 732284), reason='RuntimeError: Received unsupported message header=MessageHeader(type=<MessageType.error: \'error\'>, run_id=UUID(\'9dd85457-e49e-44c5-b9bf-7fa995c25d9c\'), id=\'00-9dd85457e49e44c5b9bf7fa995c25d9c-f1305ea3e004f272-01\', parent_id=\'00-9dd85457e49e44c5b9bf7fa995c25d9c-bba3b24cf8250e46-01\', version=\'1.0\', created_at=datetime.datetime(2023, 2, 15, 3, 27, 26, 702399)) content=ErrorContent(status=<OpStatusType.failed: \'failed\'>, ename="<class \'RuntimeError\'>", evalue=\'Traceback (most recent call last):\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 121, in run_op\
    return factory.build(spec).run(input)\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 111, in run\
    stac_results = self._call_validate_op(**{**items, **raw_items})\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 75, in _call_validate_op\
    results = self.callback(**kwargs)\
  File "/app/ops/list_sentinel1_products/list_sentinel1_products_pc.py", line 28, in list_sentinel1_products\
    raise RuntimeError(\
RuntimeError: No product found for time range (datetime.datetime(2022, 4, 1, 0, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2022, 6, 30, 0, 0, tzinfo=datetime.timezone.utc)) and 35 geometries\
\', traceback=[\'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 306, in run_op_from_message\
    out = self.run_op_with_retry(content, message.run_id)\
\', \'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 404, in run_op_with_retry\
    raise RuntimeError("".join(ret.format()))\
\']). Aborting execution.', status='failed'),
```

**Comment by robertomest** [comment]
Hi @NicholasBerryman, this error indicates that there is not Sentinel-1 data available for this time range. I just checked the Planetary Computer API and we only have products for the following dates:
```python
[datetime.datetime(2022, 12, 21, 10, 35, 9, 711619, tzinfo=tzutc()),
 datetime.datetime(2022, 12, 2, 10, 43, 18, 4437, tzinfo=tzutc()),
 datetime.datetime(2022, 11, 8, 10, 43, 18, 241944, tzinfo=tzutc()),
 datetime.datetime(2022, 10, 27, 10, 43, 18, 820429, tzinfo=tzutc()),
 datetime.datetime(2022, 10, 15, 10, 43, 19, 63514, tzinfo=tzutc()),
 datetime.datetime(2022, 10, 3, 10, 43, 18, 648094, tzinfo=tzutc()),
 datetime.datetime(2022, 9, 28, 10, 35, 11, 753346, tzinfo=tzutc()),
 datetime.datetime(2022, 9, 16, 10, 35, 11, 421601, tzinfo=tzutc()),
 datetime.datetime(2022, 8, 16, 10, 43, 17, 485506, tzinfo=tzutc())]`
```

I also checked the response from ESA's Scihub API and there were similar dates (from middle of August onwards), so I don't think it's an issue with Planetary Computer specifically.

I wonder if this is related to the issue with Sentinel-1B (which now out of commission). Now that the constellation only has one satellite, the capture regions and revisit rates were changed, see this link for some information about it https://sentinel.esa.int/web/sentinel/missions/sentinel-1/observation-scenario.

This is the previous coverage and revisit rate map
![old](https://sentinel.esa.int/documents/247904/4748961/Sentinel-1-Repeat-Coverage-Frequency-Geometry-2021.jpg)

This is the new one
![image](https://user-images.githubusercontent.com/4806997/219124357-62c091a2-84cb-4f3c-a0f4-f1bdfdeb083c.png)


Regardless, it seems like there is no Sentinel-1 data for that region in that time range, so there isn't much we can do about that. As an alternative, you could try the interpolation-based SpaceEye workflow, which only uses Sentinel-2 data. Let me know if there is something else I can do for you.

**Comment by NicholasBerryman** [comment]
Thanks for the explanation. I hadn't realised that coverage was affected by the Sentinel-1b outage, not just frequency.
