### ISSUE TITLE
connection error: connection refused to port 30000

### ISSUE THREAD

**Issue by mursaleen-bkk** [microsoft/farmvibes-ai#49]
I have completely installed the FarmVibes.AI on Azure server It was working correctly. I also Run 5 to 7 workflows. but now it gives the connection error. The error is " HTTPConnectionPool(host='172.18.0.2', port=30000): Max retries exceeded with url: /v0/workflows (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f585fb20>: Failed to establish a new connection: [Errno 111] Connection refused')) "
I also attached the details of the Error.
[Error_details.txt](https://github.com/microsoft/farmvibes-ai/files/10793781/Error_details.txt)

**Comment by richstep** [comment]
I got the same error and fixed it by running:
**bash farmvibes-ai.sh restart**

Which gave the output:
> deployment.apps/terravibes-rest-api scaled
pod "terravibes-rest-api-57db88b46c-q7vwc" deleted
deployment.apps/terravibes-rest-api scaled
Waiting for deployment "terravibes-rest-api" rollout to finish: 0 of 1 updated replicas are available...
deployment "terravibes-rest-api" successfully rolled out
deployment.apps/terravibes-orchestrator scaled
pod "terravibes-orchestrator-656cbf6fff-nsq82" deleted
deployment.apps/terravibes-orchestrator scaled
Waiting for deployment "terravibes-orchestrator" rollout to finish: 0 of 1 updated replicas are available...
deployment "terravibes-orchestrator" successfully rolled out
deployment.apps/terravibes-cache scaled
pod "terravibes-cache-54c779c59-j9cst" deleted
deployment.apps/terravibes-cache scaled
Waiting for deployment "terravibes-cache" rollout to finish: 0 of 1 updated replicas are available...
deployment "terravibes-cache" successfully rolled out
deployment.apps/terravibes-worker scaled
pod "terravibes-worker-6d8b649b5b-8d5mv" deleted
pod "terravibes-worker-6d8b649b5b-k7djf" deleted
pod "terravibes-worker-6d8b649b5b-nv6m2" deleted
deployment.apps/terravibes-worker scaled
Waiting for deployment "terravibes-worker" rollout to finish: 2 out of 3 new replicas have been updated...
Waiting for deployment "terravibes-worker" rollout to finish: 0 of 3 updated replicas are available...
Waiting for deployment "terravibes-worker" rollout to finish: 1 of 3 updated replicas are available...
Waiting for deployment "terravibes-worker" rollout to finish: 2 of 3 updated replicas are available...
deployment "terravibes-worker" successfully rolled out
FarmVibes.AI REST API is running at http://172.18.0.2:30000

**Comment by mursaleen-bkk** [comment]
@richstep can I ask that how much it take time to complete because I have run it on friday and still it's running.  
The image of process is given below: 
![image](https://user-images.githubusercontent.com/117431087/221486385-74cf7b80-1258-4f22-b78b-6791dfd6b9ff.png)

**Comment by renatolfc** [comment]
@mursaleen-bkk, may I ask for the output of the `df -h` command?

Also, can you please share the output of running `docker logs k3d-farmvibes-ai-server-0`?

Thanks!

**Comment by rafaspadilha** [comment]
Closing this issue for now. From the other issues opened by @mursaleen-bkk, it seems they were able to setup FarmVibes.AI. 

@mursaleen-bkk, feel free to reopen the issue if that is not the case.
