### ISSUE TITLE
Can't setup the worker after destroy

### ISSUE THREAD

**Issue by iharshulhan** [microsoft/farmvibes-ai#53]
I have previously installed the farmvibes-ai and run some tasks successfully, but at some point it started to give connection refused or 500 errors:
```HTTPConnectionPool(host='172.19.0.2', port=30000): Max retries exceeded with url: /v0/runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0b6cdada0>: Failed to establish a new connection: [Errno 111] Connection refused' ```

I have tried to stop/start the cluster, but it didn't help. After that I tried to destroy it and then install again, however I get the following error when trying to setup the cluster:
```
 Deploying the Dapr control plane to your cluster...
✅  Success! Dapr has been installed to namespace dapr-system. To verify, run `dapr status -k' in your terminal. To get started, go here: https://aka.ms/dapr-getting-started
Installing redis in the cluster...
statefulset.apps/redis-replicas scaled
Installing rabbitmq in the cluster...
^[[B^[[BError: INSTALLATION FAILED: timed out waiting for the condition
Failed to install rabbitmq in k8s cluster ❌
Error from server (BadRequest): pod redis-master-0 does not have a host assigned
Error from server (BadRequest): pod redis-master-0 does not have a host assigned
```

I have also tried to clean up the `.config/farmvibes-ai/`, `.kube` and `.k3d` folders, but it didn't help.

**Comment by renatolfc** [comment]
If you run `docker stop k3d-farmvibes-ai-serverlb k3d-farmvibes-ai-server-0 k3d-farmvibes-ai-registry.localhost` you should be able to stop all services.

The command `docker rm k3d-farmvibes-ai-serverlb k3d-farmvibes-ai-server-0 k3d-farmvibes-ai-registry.localhost` should allow you to delete the cluster.

If you can, please share the output of `docker logs k3d-farmvibes-ai-server-0`.

**Comment by iharshulhan** [comment]
Yes, I've tried deleting the services as well. I've attached the logs
[logs.txt](https://github.com/microsoft/farmvibes-ai/files/10824101/logs.txt)

**Comment by renatolfc** [comment]
Thanks for sharing the logs. Will analyze them.

Are you able to recreate a cluster after deleting the individual containers?

**Comment by renatolfc** [comment]
@iharshulhan, from looking at the logs, looks like k3d is under disk pressure. How full is your disk there? (The output of `df -h`.)

**Comment by iharshulhan** [comment]
No, I'm not. I can see the containers appearing in the docker while setup is running, but then it fails with the same error and they are stopped:
```
Installing rabbitmq in the cluster...
E0224 13:31:30.699003   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:30.712449   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:30.992132   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:30.997496   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.007208   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.009850   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.014913   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.021951   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.033744   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.034761   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.041707   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.047921   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.053529   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.059946   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.066667   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.072413   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.083565   83016 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0224 13:31:31.084413   83016 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Error: INSTALLATION FAILED: timed out waiting for the condition
Failed to install rabbitmq in k8s cluster ❌
```

**Comment by iharshulhan** [comment]
> @iharshulhan, from looking at the logs, looks like k3d is under disk pressure. How full is your disk there? (The output of `df -h`.)

There is still 40G available:
/dev/nvme0n1p3  916G  830G   39G  96% /

At the moment the cache of farmvibes takes about ~640GB

**Comment by renatolfc** [comment]
Is that running on an `ext4` filesystem? By default, `ext4` reserves 5% of the filesystem to the root user.

Considering your fs has `916GiB` total space, that'd give ~`45.8 GiB` of reserved space to the root user, which is pretty close to the free `39 GiB` you're seeing.

**Comment by iharshulhan** [comment]
> Is that running on an `ext4` filesystem? By default, `ext4` reserves 5% of the filesystem to the root user.
> 
> Considering your fs has `916GiB` total space, that'd give ~`45.8 GiB` of reserved space to the root user, which is pretty close to the free `39 GiB` you're seeing.

Yes, you were right it worked after freeing some memory. Feel free to close the issue. Thanks! 

As a follow up question, Is there a  clean up agent in farmvibes, which would remove unused cache data to free up space? I'm trying to run the crop_cycles calculation for a small polygon (~2000sq metres), but it uses hundreds of gigabytes to do that.

**Comment by renatolfc** [comment]
> As a follow up question, Is there a clean up agent in farmvibes, which would remove unused cache data to free up space? I'm trying to run the crop_cycles calculation for a small polygon (~2000sq metres), but it uses hundreds of gigabytes to do that.

Not right now. We are working on that feature, though. Should land in the repos in a month, give or take. (CC @msplants)

**Comment by renatolfc** [comment]
BTW: You can change the reserved space percentage with `tune2fs -m <percentage> /dev/nvme0n1p3`.
