### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Shourya13** [microsoft/farmvibes-ai#65]
After updating the latest code from FarmVibes.AI GitHub and recreating complete environment again, we have been facing connection error issues while running the notebooks.

E.g., below is an error code for Hello World workflow execution while Terravibes rest APIs are working fine. @http://172.18.0.3:30000/v0/docs

HTTPError: 400 Client Error: Bad Request for url: http://172.18.0.3:30000/v0/runs. Unable to run workflow with provided parameters. HTTPConnectionPool(host='127.0.0.1', port=3500): Max retries exceeded with url: /v1.0/state/statestore/runs?metadata.partitionKey=eywa (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa5188af250>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
Few other observations:
1.	Bash farmvibes.AI.sh setup gives success after running the script, but it constantly gives a few errors towards the end of the script execution, and we get a connection error while running any notebook, including hellowold.
2.	Bash farmvibes.Ai.sh start scripts take time to complete, and we mostly need to stop it (please refer to the attached screen shot).
3. 	Even earlier ( with old code) we were able to run the other notebooks, but it use to take long time to download the data ( e.g. – harvest prediction, weed management, land degradation etc.)

![img2](https://user-images.githubusercontent.com/27403023/224295137-c883ce4d-249c-4b1a-ae31-b72d75f0808c.png)
![img1](https://user-images.githubusercontent.com/27403023/224295145-623fa6ab-eb0f-46d3-a763-cb7034cde99f.png)

System specs: 
Memory : 16GB
Processors : 4
Hard disk (SCSI) : 512GB
Free space : 261 GB

**Comment by rafaspadilha** [comment]
Hi, @Shourya13. Thank you for using FarmVibes.AI and reporting this issue. We have made a new release updating the cluster setup to make its configuration less opaque and increase its reliability during creation. 

Please, could you pull the new changes and update your cluster. Let us know if the issues still persist.

**Comment by Shourya13** [comment]
Hi @rafaspadilha. Thanks for the support. When we tried the updated code, we started getting the following errors.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/27403023/225227452-6d39daee-e68a-4780-a11e-f99e546b8177.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/27403023/225227473-123523b3-5cef-4581-916c-617a6701b0b4.png)

**Comment by rafaspadilha** [comment]
@Shourya13 may I ask for the output of the `df -h` command?

**Comment by zaned897** [comment]
I had the same problem while installing on a VM, changing farmvibes storage path and docker daemon path solves the problem

**Comment by rafaspadilha** [comment]
Errors like this may happen if the disk space allocated for the cache or for storing our docker images are not enough. Thank you for reporting this, @zaned897. 

@Shourya13, I'll close this issue for now. Feel free to reopen it if you are still facing this problem.
