### ISSUE TITLE
Space requirements for Spaceeye Cloud Removal?

### ISSUE THREAD

**Issue by madhavaggar** [microsoft/farmvibes-ai#77]
After setting up the sentinel-spaceye notebook environment & running the code, the process fails. Currently, I am using the recommended space of ~500GB. But this is clearly not enough. The cluster crashes at the preprocess_s2_improved_masks step. Current RAM: 16GB, Disk Space: ~500GB (100% consumed).

Need the Spaceye pipeline for cloud removal on a large number of data points (500), regions (roughly 20km2 in the area), and times (average period = 20 days). What are the suggested system requirements for this task?

**Comment by robertomest** [comment]
Hello @madhavaggar, the recommended space would be to run the notebook with the sample inputs. Can you clarify what you mean by 500 data points? Do you mean 500 different regions, each with their own time period? Are these regions near each other?

For 20 days there should be on average 4 products for a Sentinel-2 tile. If all points require different products, this would mean downloading 2000 Sentinel-2 tiles, each tile using a few GB of disk space. If the regions are near each other (in the same tile) and the time range is the same, FarmVibes will automatically reuse the already downloaded data, so no recomputation will be made and the necessary disk space we be reduced accordingly.

It's hard to estimate exactly how much disk space a workflow will require, but if you provide a bit more information I can try to help.

**Comment by madhavaggar** [comment]
I would first like to know about the _sentinel_spaceye.ipynb_ notebook provided as a sample. It consumed approx. 500GB of disk space and crashed at the **preprocess_s2_improved_masks** step in the "Working with cloud masks" section. 

Could you give specifics on how much space this pipeline uses (or should use) for the **sample notebook** provided? I believe that would help a lot of others figure out the disk space that will be required.

The pipeline I want to run has approx 500 data points spread apart in time and space. Each data point representing the centroid of a region has a variation of 0.05 either in Latitude or Longitude as compared to every other data point. So they are definitely not close to each other. Each region is approximately 100km^2 in radius.

**Comment by rafaspadilha** [comment]
Closing this issue for now. @madhavaggar, feel free to reopen it if you have more questions.
