### ISSUE TITLE
It appears that there could be a problem with the method used for calculating the RMSE value in deepMC.

### ISSUE THREAD

**Issue by ziwonSeo-lab** [microsoft/farmvibes-ai#84]
There seems to be an issue with calculating the RMSE value in cell 33 of the deepmc/mc_forecast.ipynb notebook. By setting the squared option of the mse function to **False**, the RMSE value is returned directly, eliminating the need for a separate math.sqrt operation. Nonetheless, the value currently being displayed appears to be the result of an additional sqrt on peration performed on the RMSE value. Would you kindly verify and address this matter?
![rmse](https://user-images.githubusercontent.com/77081711/230808443-01bbd6fb-d447-47c2-804d-38bcccfc7e7a.png)

**Comment by v-ngangarapu** [comment]
Thanks for contacting and letting us know about the issue.

Yes, math.sqrt is not required. 
Will fix this issue.
