### ISSUE TITLE
Error while setting up farmvibes.ai cluster

### ISSUE THREAD

**Issue by iam-kuldeep04** [microsoft/farmvibes-ai#95]
On below command:
`bash farmvibes-ai.sh setup`

got below error :

> module.services.kubernetes_deployment.worker: Still creating... [9m20s elapsed]
> module.services.kubernetes_deployment.worker: Still creating... [9m30s elapsed]
> module.services.kubernetes_deployment.worker: Still creating... [9m40s elapsed]
> module.services.kubernetes_deployment.worker: Still creating... [9m50s elapsed]
> module.services.kubernetes_deployment.worker: Still creating... [10m0s elapsed]
> 
> 
> Error: Waiting for rollout to finish: 1 replicas wanted; 0 replicas Ready
> 
> with module.services.kubernetes_deployment.worker,
>   on ../services/worker.tf line 15, in resource "kubernetes_deployment" "worker":
>   15: resource "kubernetes_deployment" "worker" {
>   Error: timed out waiting for the condition on deployments/terravibes-rest-api

**Comment by rafaspadilha** [comment]
Hi, Kuldeep. Thank you for raising this issue.

You might see this error if the deployment times out when getting the worker pod up and running. Tuning the amount of time we should wait for deployments is tricky, as they will depend on each user's machine.

If `~/.config/farmvibes-ai/kubectl get pods`  shows that all pods are running, you should be good to go.
