### ISSUE TITLE
I have a question about the DeepMC latitude-longitude difference code.

### ISSUE THREAD

**Issue by ziwonSeo-lab** [microsoft/farmvibes-ai#96]
In the DeepMC paper, location information was incorporated by including the difference in latitude and longitude as part of the input data, along with the application of the WPD (Weather Prediction Decomposition) technique, to predict future climate. However, it appears that the provided code does not include these components.

Furthermore, if we assume that the model is trained only for a single location, it is likely that the fixed latitude and longitude differences would not have a significant impact on the model's performance. However, when training for multiple locations, such differences could become meaningful training factors.

Could you please confirm whether these components were intentionally not included in the provided code?

**Comment by peeyush-kumar** [comment]
Hi @ziwonSeo-lab, For a single location the latitude and longitude does not add any extra information. That is why these components were removed. 

When training with multiple locations, our observations are a little more complex. The  locational information becomes important but it requires some additional steps for efficient transfer learning within the DeepMC context. We have an ongoing work on this, which will be released soon. 

If you have any ideas or work in this context of multiple locational learning, would love to hear it!
