### ISSUE TITLE
running specific indices on specific pods

### ISSUE THREAD

**Issue by click2cloud-amit** [microsoft/farmvibes-ai#99]
Can we incorporate something like pod affinity into the workflow for indices so that the indices that take a long time would be handled by a different pod to speed up execution and allow us to obtain the indices values more quickly?

**Comment by rafaspadilha** [comment]
Hi, @click2cloud-amit. Pod affinity is not on our roadmap for now. 

Subtasks are added to a queue from which free workers fetch them for execution. The output of a workflow run will be available only after all subtasks complete. Consequently, if you have multiple indices within a single workflow, you will only be able to retrieve the result of a particular index once all of them finish computation.

A workaround to this is to split a workflow with multiple indices to several single-index workflow runs (leveraging the caching mechanism to avoid redownload/reprocessing the input raster). For next release, we are improving the monitor tool to allow a user to simultaneously track the progress of several workflows. 

Even though, subtask execution is still being parallelized among available workers, this might aid in tracking and retrieving outputs as the workflow run finishes.
